@WebApi_HostAddress = https://localhost:5003


POST {{WebApi_HostAddress}}/api/v3/users
Accept: application/json
Content-Type: application/json
{
  "name" : "John Obe",
  "userName" : "JohnO",
  "email" : "John@Hotmail.com",
  "password" : "Johnson"
}

###

PUT {{WebApi_HostAddress}}/api/v3/users
Accept: application/json
Content-Type: application/json
{
  "name" : "1",
  "userName" : "user1",
  "password" : "password1",
   "email" : "Some@Hotmail.com"
}

###

GET {{WebApi_HostAddress}}/api/NameBasic
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/NameBasic/nm0000138 
