@WebApi_HostAddress = https://localhost:5003


POST {{WebApi_HostAddress}}/api/v3/users
Accept: application/json
{
  "name" : "John Johnson",
  "userName" : "JohnJ",
  "password" : "Johnson"
}

###

PUT {{WebApi_HostAddress}}/api/v3/users
Accept: application/json
{
  "userName" : "JohnJ",
  "password" : "Johnson"
}

###

GET {{WebApi_HostAddress}}/api/NameBasic
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/NameBasic/nm0000138 
